environment: prod

deployment:
  image:
    tag: 0
  replicas: 1
  env:
    redis_host: ngao-nghe-vn-prod-elascache-rep-group.7x8qwo.ng.0001.euc1.cache.amazonaws.com # This value was modified by the deploy-infra pipeline